In [3]:
import pandas as pd
import openpyxl
import xlrd

In [5]:
data = pd.read_excel('data/raw/ejemplo_datos.xlsx', engine='openpyxl')

In [28]:
data

,TipoDoc,Documento,LineaDoc,Factura,LineaFra,Fecha,Cliente,PaisCliente,PaisDestino,Departamento,...,Combinacion,Color,Ancho,CN8,Composicion,Lote,Pieza,MetroPieza,MetrosReducidos,MetrosDefectuosos
0,F,657453,1,657453,1,2020-01-24 00:00:00.000,999544,TN,TN,2,...,0,0,145,58012200,1151,50-0404 / 001 R 01 2 2019,31,5.0,5.0,0.0
1,F,657454,1,657454,1,2020-01-24 00:00:00.000,999663,NL,PT,2,...,0,8196,145,52094900,1151,11-2193 / 000 4 2019,6,5.0,5.0,0.0
2,F,657455,1,657455,1,2020-01-24 00:00:00.000,999984,DE,DE,3,...,0,45531,160,55142200,3743,35-0121 / 001 2 2019,19,1.0,1.0,0.0
3,F,657455,2,657455,2,2020-01-24 00:00:00.000,999984,DE,DE,3,...,0,65141,160,55142200,3743,48-0114 / 001 2 2019,10,1.0,1.0,0.0
4,F,657455,3,657455,3,2020-01-24 00:00:00.000,999984,DE,DE,3,...,0,78666,160,55142200,3743,35-0123 / 001 2 2019,14,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,F,657468,1,657468,1,2020-01-27 00:00:00.000,330126,ES,ES,3,...,0,75004,160,55142200,10,50-0109 / 002 2 2019,5,88.5,88.5,0.0
413,F,657468,1,657468,1,2020-01-27 00:00:00.000,330126,ES,ES,3,...,0,75004,160,55142200,10,50-0109 / 002 2 2019,6,36.7,36.7,0.0
414,F,657468,1,657468,1,2020-01-27 00:00:00.000,330126,ES,ES,3,...,0,75004,160,55142200,10,50-0109 / 002 2 2019,7,36.3,36.3,0.0
415,F,657468,1,657468,1,2020-01-27 00:00:00.000,330126,ES,ES,3,...,0,75004,160,55142200,10,50-0109 / 001 2 2019,1,80.4,80.4,0.0
416,F,657468,1,657468,1,2020-01-27 00:00:00.000,330126,ES,ES,3,...,0,75004,160,55142200,10,50-0109 / 001 2 2019,2,35.8,35.8,0.0

In [37]:
class factura(object):
    
    def __init__(self, tabulear_data):
        self.info = tabulear_data
    
    @property
    def info(self):
        return self.info
    
    @info.setter
    def info(self, new_data):
        new_df = pd.DataFrame(columns=new_data.columns)
        num_datos = len(new_data)
        for i in range(num_datos):
             important_info = new_data.iloc[i,0]
        if important_info == 'F':
                important_rows = new_data.iloc[i,:]
                df_facturas = new_df.append(important_rows)
                self._info = df_facturas
                return print(df_facturas)
#to do , agruppation of the lines with the same document number

In [38]:
factura(data)

    TipoDoc Documento LineaDoc Factura LineaFra                    Fecha  \
416       F    657468        1  657468        1  2020-01-27 00:00:00.000

    Cliente PaisCliente PaisDestino Departamento  ... Combinacion  Color  \
416  330126          ES          ES            3  ...           0  75004

     Ancho       CN8  Composicion                            Lote Pieza  \
416    160  55142200           10  50-0109 / 001           2 2019     2

     MetroPieza MetrosReducidos MetrosDefectuosos
416        35.8            35.8               0.0

[1 rows x 33 columns]

In [40]:
class abono(object):
    
    def __init__(self, tabulear_data):
        self.info = tabulear_data
    
    @property
    def info(self):
        return self.info
    
    @info.setter
    def info(self, new_data):
        new_df = pd.DataFrame(columns=new_data.columns)
        num_datos = len(new_data)
        for i in range(num_datos):
             important_info = new_data.iloc[i,0]
        if important_info == 'A':
                important_rows = new_data.iloc[i,:]
                df_facturas = new_df.append(important_rows)
                self._info = df_facturas
                return print(df_facturas)

In [64]:
new_df = pd.DataFrame(columns=data.columns)

for i in range(len(data)):
          important_info = data.iloc[i,0]
if important_info == 'F':
                important_rows = data.iloc[i,:]
                df_facturas = new_df.append(important_rows)
                df_facturas